apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ht5w3toy9-go 
  janus-idp.io/tekton: ht5w3toy9-go
  backstage.io/kubernetes-id: ht5w3toy9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ht5w3toy9-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml